### ISSUE TITLE
Decode error: -17710

### ISSUE THREAD

**Issue by GB-CG** [Sappharad/MultiPatch#16]
Applying [dinopatch](https://dinosaurpla.net/download/Main/Tech/Mods/dinopatch-various-game-fixes-xdelta/WebHome/dinopatch_v2.4.xdelta) for the N64 prototype, Dinosuar Planet (`rom_crack` version) doesn't seem to work.

**Comment by Sappharad** [comment]
There doesn't seem to be any documentation for this patch, they just have a download link.
Do you know what version of XDelta it was made with?

The official XDelta hasn't been updated since January 2016, although MultiPatch is based on XDelta 3.0.1 which is from 2010. I suppose I could update to the latest version if that's what needs to be done to fix it, but the latest version 3.1.0 is not that much newer than what's in MultiPatch right now.

**Comment by GB-CG** [comment]
They used [Delta Patcher 2.0.1](https://github.com/marco-calautti/DeltaPatcher) to make the patch. Edit: v3.0.7 32bit, according to the dev.

**Comment by Sappharad** [comment]
Patch uses optional SECONDARY_DJW=1 compression flag.
"unavailable secondary compressor: DJW Static Huffman"

To be added in future release.

**Comment by Sappharad** [comment]
Commit 199a721a4a780b560b945b7162052fa1ead2030f upgrades to latest XDelta, 3.1.0
The patch linked above works, but I still need to perform additional testing to make sure nothing else broke, as well as update documentation and other things to prepare for a new release. Might have something later this month.

**Comment by Sappharad** [comment]
Released with version 2.0

**Comment by GB-CG** [comment]
Much appreciated. This also fixed the issue with the Doubutsu Banchou English translation. Thank you.
