### ISSUE TITLE
Add ability to disable XDelta checksum verification

### ISSUE THREAD

**Issue by GB-CG** [Sappharad/MultiPatch#4]
~~Most of the Goldeneye 64 XDelta patches refuse to work (I think most of them are .xdelta extensions), for example: a recent rom hack, Complex Mission, refuses to patch.~~
Turns out I had a corrupt ROM (or it might've been a byteswapped ROM). Anyway I think adding a 'disable checksum verification' would be useful for some hacks.

Edit: Hmm, debating if this is a good idea or not.

**Comment by Sappharad** [comment]
Your input file is wrong.
The error message is telling you that. Use the same ROM that was used to make the patch. XDelta patches only work on the exact same input file that the patch was created for.

**Comment by GB-CG** [comment]
But I did the same thing with another program, DeltaPatcher (Windows). I used a Goldeneye.n64 rom with a verified MD5 and the .XDelta file and it worked.

**Comment by Sappharad** [comment]
Did you have to disable checksum validation for it to work? I'm basically using an unmodified copy of XDelta, so there's no reason a valid file shouldn't work.

**Comment by GB-CG** [comment]
Yes, I disabled it. Enabling it reads, 'An error has occurred: xdelta3: target window checksum mismatch: XD3_INVALID_INPUT'.

**Comment by Sappharad** [comment]
"Target" is your source rom.
Checksum mismatch means that your source ROM is wrong.

It's the same message MultiPatch is giving you, (which you can see in Console.app if you run it while patching) except that MultiPatch doesn't let you disable validity checking. I can look into adding the ability to disable the check, but you just confirmed for me that either your input ROM is bad, or the patch itself is bad.

**Comment by GB-CG** [comment]
Maybe it's something to do with byteflipping the rom? I think adding an option to disable the check is probably a good idea?

**Comment by Sappharad** [comment]
I can add this feature some day. Thanks for requesting it.

**Comment by Sappharad** [comment]
This has been added in commit 992640c3ea47caac0d0ca1bed9a14a6d7ac557cf 
It doesn't seem to be a good idea, but it's there and it works. I tested against a patch for an NES game, applying it to the wrong region, as expected I got a valid NES rom that does not actually work.

**Comment by kommpn** [comment]
Doesn't seem to work, as I check the box, the error dialog doesn't change, also even if it us unchecked and the input file is wrong, it still give in output a bin file. 
The error is: 
`Invalid input. This typically means that the file you selected to patch is not the file your patch is intended for.`

**Comment by Sappharad** [comment]
It worked in 2018 and the logic for it is still there. Since XDelta can move things around in a file, if the input file is completely wrong then ignoring validation does not matter. The checkbox is for situations where the input file is only slightly different (like games that get minor revisions but data might be 99% identical) where a patch could still work even if the input was not identical.

An output file being created anyway is probably how XDelta command line works internally; this is a situation where I provide the Input tell it where to put the output, I'm not controlling what XDelta is doing with it.

**Comment by craftersshaft** [comment]
heavily seconding this feature, because there are countless romhacks i've tried that use this format where even after directly comparing the checksums between the rom i have and the rom it claims to work with, it won't work until i just download a completely different rom instead

edit: i forgot this repository was for exclusively a mac os app and not the other patchers i'm having issues with, my apologies
