### ISSUE TITLE
patching ppf to playstation bin file doesn't work.

### ISSUE THREAD

**Issue by pleasejust** [Sappharad/MultiPatch#6]
Patching for the most part works fine, except for ppf to a playstation bin. I've tried to get LandonRay's Symphony of the Night hack to work. I have the correct bin with the correct crc32. When I use multipatch, the bin goes from 538MB or whatever to 75MB and won't load in any emulator even though it said the patch was applied properly! Something is seriously wrong there.

**Comment by Sappharad** [comment]
Based on the forum for libPPF, which is what MultiPatch uses for PPF patches, it looks like someone reported several bugs 10 years ago and they never got fixed because it's never been updated since then:
https://sourceforge.net/p/lppf/discussion/692276/

I don't know if this is the cause of your problem or not, I have not tested this particular patch.

I can either try to fix libPPF, or just switch to a different PPF patcher. Unfortunately there doesn't appear to be another open source PPF patcher written in C or C++ that I can use. I'll decide once I get a chance to learn more about this particular patch.

**Comment by Sappharad** [comment]
I've applied the fix recommended in one of the LibPPF forum posts. I have no idea how this thing ever worked correctly for anyone before. In testing the 'bad' code it somehow managed to make APFS go crazy and kernel_task started writing data until it completely filled up my drive and the system locked up.

This new build appears to apply your patch successfully, but I'm not familiar with the game so please test and let me know how it goes.

[MultiPatch163beta.zip](https://github.com/Sappharad/MultiPatch/files/2407488/MultiPatch163beta.zip)

Thanks!

**Comment by Sappharad** [comment]
634297662b112401740df367eab8312f078c4cb1

**Comment by pleasejust** [comment]
Thanks! FYI I'm still on 10.12.6, hence HFS+. I'll try, report back.

**Comment by pleasejust** [comment]
Just tested it out. It didn't work. The cue/bin won't load into the OpenEmu library at all. Using PPFApplier didn't work either. The only way I have been able to successfully apply ppf patches is with ppf-o-matic for windows. Luckily I've got a win10 bootcamp setup. Thanks anyways.

**Comment by Sappharad** [comment]
I tested it and it worked for me. I was able to load the .cue sheet into BizHawk and the game runs. I don't know what to expect because I've never played it before, but comparing it to the unpatched version you start with 15 health instead of 30 so it seems like something happened.

You know that a .cue file I just a text file right? MultiPatch asks you to create a new file for the patched version, so you need to open the .cue in a text editor and change the name of Track1.bin in the cue sheet to whatever you called the patched version.

What is OpenEmu complaining about?

**Comment by pleasejust** [comment]
Yes, I know the cue sheet is just text. I guess I must've had a spelling mistake or something. I just tested it again, it loaded but it didn't actually apply the changes. To know if the changes were applied, when you get passed the prologue and start playing as Alucard, it will take 2 hits with your sword to kill the giant wolf instead of the usual 1. F*cken annoying that the author didn't add something to the title screen. I don't know how you started the prologue with 15 hearts. You're always supposed to start with 30. But this time I'm positive I did it 100% correct and it didn't work. Weird.

**Comment by pleasejust** [comment]
Hi, just wanted to mention that multipatch does in fact apply ppf files correctly. It turns out that romhacks not working properly with accuracy-focused emulators is a thing. Many rom hacks, especially playstation, don't work properly or at all with mednafen, hence Openemu. I don't understand how that works because isn't the point of emulators to emulate the hardware? So what are other emulators NOT doing properly that makes some rom hacks work? Why wouldn't authors make sure the hacks work in accurate emulators?

Anyways, thanks 👍

**Comment by Sappharad** [comment]
Well, if that's the case you mean specifically the beta build in this thread, because the current release clearly applied it wrong.

Thanks for confirming though!
