### ISSUE TITLE
PS1 2352 image EDC/ECC recalculation

### ISSUE THREAD

**Issue by jerkstore369** [Sappharad/MultiPatch#8]
Hi, so last time I posted, I discovered that certain PS1 hacks don't work in real hardware or certain emulators, specifically accuracy focused ones. I was browsing the megaman x6 tweaks page on romhacking.net which says that the custom patch auto-applies a PS1 2352 image EDC/ECC recalculator so that it'll work in real hardware and accurate emulators. I had no idea this was a thing. I've never read anything about this anywhere, it's like nobody knows this. No info about this was posted on, for example, the Symphony of the Night hardtype hack page about needing to do this. Strange... anyways, so I bit the bullet and downloaded virtualbox/windows 10 and used the tool on my hacked SotN bin file and I tested it out and it works flawlessly. No game freezing from killing golden medusa heads among other things.

so my request is, can you add in a recalculation tool into multipatch or something? There's one here that's windows only:
http://www.romhacking.net/utilities/1264/

which is based off of this:
https://archive.fo/tuq4u#selection-580.1-580.2

The download here comes with source code. I'm not programmer, I don't know if this is useful or possible but it's an idea and would be great if multipatch would have it. It seems to me that after patching a PS1 game, recalculating the EDC/ECC should always be done. Thanks.

**Comment by Sappharad** [comment]
I'm going to close this issue because this is out of scope for a patching application. If someone is distributing patches that create invalid ECC data, those patches are at fault and they should be correcting the data before making the patch. It shouldn't be the end user's responsibility to know how to fix a bad patch. EDC/ECC data is common to many CD image formats, it's part of the CD-ROM standard. If you directly edit data inside a disc image without modifying the ECC it means you're doing it wrong. Fortunately, the data is there for when CD drives have trouble reading areas of the disc so they can 'recover' what was originally supposed to be there. Emulators don't usually use it, because with files on a hard drive you can assume the entire file can be read just fine.

I'm actually familiar with the EDC/ECC calculation stuff, the tool I wrote to build Dreamcast GDI images also generates ECC data when you build a disc image. Prior to that, I used other tools on Windows that could generate ECC, I had never even heard of the one you linked before so it's not the only tool for that purpose. I wouldn't be surprised if there's already some kind of tool for macOS to fix ECC. If not, perhaps you can find a tool that converts 2352 to 2048 sector images, once you convert back to 2352 the ECC data will be correct. Or don't convert back at all - When you burn a 2048 sector image your disc burner is going to generate the missing ECC data as it writes to the disc.
